github:
  description:   "ASF Infrastructure Catalog Service"
  homepage:      https://infra.apache.org/
  collaborators: []
  autolink_jira:
    - INFRA
  custom_subjects:
    new_issue: "{repository}/#{issue_id} created"
    close_issue: "{repository}/#{issue_id} closed"
    catchall: "{repository}/#{issue_id} updated"
    new_discussion: "Created: Discussion {repository}: {title}"
    edit_discussion: "Edited: Discussion {repository}: {title}"
    close_discussion: "Closed: Discussion {repository}: {title}"
    close_discussion_with_comment: "Closed: Discussion with comment {repository}: {title}"
    reopen_discussion: "Reopened: Discussion {repository}: {title}"
    new_comment_discussion: "Commented: Discussion {repository}: {title}"
    edit_comment_discussion: "Edited a comment: Discussion {repository}: {title}"
    delete_comment_discussion: "Deleted a comment: Discussion {repository}: {title}"
  labels:
    - infrastructure
    - catalog
notifications:
  commits:              commits@infra.apache.org
  pullrequests:         commits@infra.apache.org
  issues:               commits@infra.apache.org
  discussions:          commits@infra.apache.org
  pullrequests_bot_dependabot: commits@infra.apache.org
